dist: trusty
sudo: required
language: ocaml
cache:
  apt: true
  directories:
  - $HOME/.opam
addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
    - aspcud
env:
  global:
  - NJOBS=4
  # system is == 4.02.3
  - COMPILER="system"
branches:
  only:
  - master
  - improve-dep
notifications:
  email:
    recipients:
    - wmansky@cs.princeton.edu
git:
  depth: 3

install:
- "[ -e .opam ] || opam init -j ${NJOBS} --compiler=${COMPILER} -n -y"
- eval $(opam config env)
- opam config var root
- opam install -j ${NJOBS} -y coq=8.6 ${EXTRA_OPAM}
- opam list

jobs:
  include:
  - stage: setup
    script:
    - echo 'Building VST...' && echo -en 'travis_fold:start:VST.build\\r'
    - make -j ${NJOBS} IGNORECOQVERSION=true
    - echo -en 'travis_fold:end:VST.build\\r'
  - stage: test
    script: make -j ${NJOBS} IGNORECOQVERSION=true progs
  - script: make -j ${NJOBS} IGNORECOQVERSION=true hmacdrbg
  - script: travis_wait make -j ${NJOBS} IGNORECOQVERSION=true mailbox
