---
name: CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        coq_version:
          # See https://github.com/coq-community/docker-coq/wiki for supported images
          - '8.12'
          - '8.13'
        opam_name:
          - coq-vst
          - coq-vst-32
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@2.1.1
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: ${{ matrix.opam_name }}.opam
          coq_version: ${{ matrix.coq_version }}
          custom_script: |
            # This mostly follows https://github.com/coq-community/docker-coq-action/tree/v1.0.0
            startGroup Opam config
              opam repo add -y prerelease file://$WORKDIR/opam-prerelease
              opam config list; opam repo list; opam list
            endGroup
            startGroup Build dependencies
              opam pin add -n -y -k path $PACKAGE $WORKDIR
              opam update -y
              opam install -y -j 2 $PACKAGE --deps-only
            endGroup
            startGroup Build
              # Temporary solution to coq-community/docker-coq-action#23
              # Added -t flag to the default script
              opam install -y -v -t -j 2 $PACKAGE
              opam list
            endGroup
            startGroup Uninstallation test
              opam remove $PACKAGE
            endGroup
